kind: pipeline
name: default
type: docker

steps:

  - name: docker tag
    image: plugins/docker
    settings:
      repo: fs/frontend
      registry: registry:5000
        - latest
    when:
      branch:
        exclude: [master, release/*]
        event: push