kind: pipeline
name: default
type: docker

steps:

  - name: build image
    image: plugins/docker
    network_mode: host
    environment:
      VUE_APP_GRAPHQL_HTTP:
        from_secret: GRAPHQL_HTTP
      VUE_APP_GRAPHQL_WS:
        from_secret: GRAPHQL_WS
      VUE_APP_DEV_SERVER_PROXY:
        from_secret: DEV_SERVER_PROXY
      VUE_APP_API_PREFIX:
        from_secret: API_PREFIX
      VUE_APP_SENTRY_ENABLE:
        from_secret: SENTRY_ENABLE
      VUE_APP_SENTRY_DSN:
        from_secret: SENTRY_DSN
      VUE_APP_SENTRY_SERVER_NAME:
        from_secret: SENTRY_SERVER_NAME
      VUE_APP_SENTRY_ENVIRONMENT:
        from_secret: SENTRY_ENVIRONMENT
      VUE_APP_GOOGLE_MAP_API_KEY:
        from_secret: GOOGLE_MAP_API_KEY
    settings:
      repo: localhost:5000/fs/frontend
      registry: localhost:5000
      insecure: true
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: [ "${DRONE_BUILD_NUMBER}", latest ]
      build_args_from_env:
        - VUE_APP_GRAPHQL_HTTP
        - VUE_APP_GRAPHQL_WS
        - VUE_APP_DEV_SERVER_PROXY
        - VUE_APP_API_PREFIX
        - VUE_APP_SENTRY_ENABLE
        - VUE_APP_SENTRY_DSN
        - VUE_APP_SENTRY_SERVER_NAME
        - VUE_APP_SENTRY_ENVIRONMENT
        - VUE_APP_GOOGLE_MAP_API_KEY
    when:
      branch:
        exclude: [master, release/*]
        event: push

  - name: push image
    image: plugins/docker
    network_mode: host
    settings:
      repo: localhost:5000/fs/frontend
      registry: localhost:5000
      insecure: true
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: [ "${DRONE_BUILD_NUMBER}", latest ]
    when:
      branch:
        exclude: [master, release/*]
        event: push