version: '3.3'

services:
  fs-frontend:
    container_name: fs-frontend
    restart: always
    build: .
    env_file: .env
    image: fs-frontend
    networks:
      - shopbackend_discovery
    ports:
      - '80:80'

networks:
  shopbackend_discovery:
    external: true
