version: '3.3'

services:
  fs-frontend:
    container_name: fs-frontend
    restart: always
    build: .
    volumes:
      - /opt/node_app/app/node_modules
    image: fs-frontend
    networks:
      - shopbackend_discovery
    ports:
      - '80:3000'

networks:
  shopbackend_discovery:
    external: true