FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:stable-alpine as production-stage

ARG VUE_APP_GRAPHQL_HTTP
ENV VUE_APP_GRAPHQL_HTTP $VUE_APP_GRAPHQL_HTTP

ARG VUE_APP_GRAPHQL_WS
ENV VUE_APP_GRAPHQL_WS $VUE_APP_GRAPHQL_WS

ARG VUE_APP_DEV_SERVER_PROXY
ENV VUE_APP_DEV_SERVER_PROXY $VUE_APP_DEV_SERVER_PROXY

ARG VUE_APP_API_PREFIX
ENV VUE_APP_API_PREFIX $VUE_APP_API_PREFIX

ARG VUE_APP_SENTRY_ENABLE
ENV VUE_APP_SENTRY_ENABLE $VUE_APP_SENTRY_ENABLE

ARG VUE_APP_SENTRY_DSN
ENV VUE_APP_SENTRY_DSN $VUE_APP_SENTRY_DSN

ARG VUE_APP_SENTRY_SERVER_NAME
ENV VUE_APP_SENTRY_SERVER_NAME $VUE_APP_SENTRY_SERVER_NAME

ARG VUE_APP_SENTRY_ENVIRONMENT
ENV VUE_APP_SENTRY_ENVIRONMENT $VUE_APP_SENTRY_ENVIRONMENT

ARG VUE_APP_GOOGLE_MAP_API_KEY
ENV VUE_APP_GOOGLE_MAP_API_KEY $VUE_APP_GOOGLE_MAP_API_KEY

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
